/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AIController */

#ifndef _Included_AIController
#define _Included_AIController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AIController
 * Method:    predict
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_AIController_predict
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
